# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: xcodebuild -scheme SnabbleNetwork -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' test
